MCDReforged/PluginCatalogue

readme.md
readme_cn.md

add Welcomer MCDRClear and TitleAPI

Add three plugins

---

readme.md
readme_cn.md

Change link and Add ServerOccupancyAPI

---

readme.md
readme_cn.md

Add WebsocketBlh 添加了 WebsocketBlh

Add WebsocketBlh

---

readme.md
readme_cn.md

you can change ownership of cats and dogs that owned by you

Add petmove

---

readme.md
readme_cn.md

Added MCDR-get

---

readme.md
readme_cn.md

Add currency

---

readme.md
readme_cn.md

add RepairManager

---

readme.md
readme_cn.md

Add multi_whitelist and correct some chinese in english README.md

---

readme.md
readme_cn.md

增加Online插件

---

readme.md
readme_cn.md

增加seed、mcwl、kick插件

---

readme.md
readme_cn.md

在游戏公屏打出BV，AV或B站视频链接，得到视频的点赞，弹幕，评论，收藏，硬币，分享和播放量，并给出直接跳转浏览器的按钮和复制BV，AV或B站视频链接的按钮

BilibiliInfo 一个哔哩哔哩插件

---

readme.md
readme_cn.md

- 添加插件：[**SeedR**](https://github.com/Van-Involution/MCDR-Plugins)
- 重制自 **[MCDReforged](https://github.com/MCDReforged)/[Seed](https://github.com/MCDReforged/Seed)**
- 适配 **MCDR 1.x**
- 回复具有原版风格并经过翻译的消息
- 修改标题下语言切换链接（和[MCDR](https://github.com/Fallen-Breath/MCDReforged)文档保持一致）
- 修改前：
- `readme.md`：[中文]()
- `readme_cn.md`：[English]()
- 修改后：
- `readme.md`：**English** | [中文]()
- `readme_cn.md`：[English]() | **中文**

[SeedR] 种子获取 - 重制版（外加文档细节美化）

---

readme.md
readme_cn.md

一个让维度之间传送更方便的插件
`!!overworld` 在地狱，传送到主世界对应坐标（地狱坐标*8）,在末地，传送至当前坐标
`!!overworld <x> <y> <z>` 传送到主世界指定坐标
`!!nether` 在主世界，传送到地狱对应坐标（主世界坐标/8）,在末地，传送至当前坐标
`!!nether <x> <y> <z>` 传送到地狱指定坐标
`!!end` 传送到末地祭坛上空(0,100,0)
`!!end <x> <y> <z>` 传送到末地指定坐标

添加了 TpDimension 插件

---

readme.md
readme_cn.md

Add quick_run_cmd

---

readme.md
readme_cn.md

Add CwdHelper

---

readme.md
readme_cn.md

提交 Markit 插件

---

readme.md
readme_cn.md

提交了SeenR（seen的重置），LazyTP（快速传送），WESchem（各子服间快速拷贝WE原理图）

提交SeenR, LazyTP和WESchem三个插件

---

readme.md
readme_cn.md

一个兼容MCDR 1.x 的传送插件，修复 tpHelper 中存在的各项 bug 并添加家园/出生点/回溯传送相关功能。

增加 Telekinesis 插件

---

readme.md
readme_cn.md

and i make it in only 1 minute

add plugin PythonIsPlugin

---

readme.md
readme_cn.md

Add AutoZipBackup plugin

---

readme.md
readme_cn.md

> 一个MCDR插件+Java库，允许用户通过该库实现QQ，MC双向聊天，服务器控制等功能
会进行长期维护，添加并优化各种功能

Add MCDReforged-Remote Plugin

---

readme.md
readme_cn.md

Add ChatBridgeReforged to Plugin Catalogue

Add ChatBridgeReforged

---

readme.md
readme_cn.md

fix the path of #110

---

readme.md
readme_cn.md

added GitBackUp(zyxgad) plugin

---

readme.md
readme_cn.md

added WhiteList(zyxgad)

---

readme.md
readme_cn.md

Reverts MCDReforged/PluginCatalogue#121

Revert "added plugin 'RawInput'"

---

readme.md
readme_cn.md

更改 WikiRequest 的描述文本（再次）

---

readme.md
readme_cn.md

Reverts MCDReforged/PluginCatalogue#135

Revert "Add some plugins"

---

plugins/mirror_server_sync/plugin_info.json

啊吧 一个自己写的插件来同步不同服务器之间的存档
README还没写完

Add Mirror Server Sync Plugin

---

plugins/offline_whitelist/plugin_info.json

- offline whitelist plugin
- info & usage : https://github.com/skuzow/offline-whitelist

feat: offline whitelist

---

plugins/simple_translator/plugin_info.json

- simple translator plugin
- info & usage : https://github.com/skuzow/simple-translator

feat: simple translator

---

plugins/kpi/plugin_info.json

Add plugin `kpi`

---

plugins/mirror_control/plugin_info.json

使可以直接跳转到[English version]而不会404

mirror control: change readme file

---

readme.md
readme_cn.md

- 随 MCDR 迭代，应当停止对旧插件目录的支持
- 优化 README 格式和表述问题

优化 README 表述

---

plugins/allow_suicide/plugin_info.json
plugins/welcome_msg/plugin_info.json

Allow player suicide without op

Allow Suicide

---

.github/workflows/checklist.yml
.github/workflows/plugin_check.yml
.github/workflows/scripts/pr_check.py
scripts/pr_check.py

- Fixed auto comment
- Fixed plugin check

Better Github Actions

---

plugins/join_motd_next/plugin_info.json

Add plugin join MOTD next

---

plugins/showshowway/plugin_info.json

Add plugin ShowShowWay

---

plugins/ledger_cleaner/plugin_info.json

增加 ledger_cleaner 插件

---

plugins/ipanel_mcdreforged/introduction-zh_cn.md
plugins/ipanel_mcdreforged/plugin_info.json

Briefly clarify plugin features in the introduction, and clarify plugin usage in detail in the …

feat: 添加`ipanel_mcdreforged`插件

---

plugins/ipanel_mcdreforged/introduction-zh_cn.md
plugins/ipanel_mcdreforged/plugin_info.json

Briefly clarify plugin features in the introduction, and clarify plugin usage in detail in the …

feat: 更改链接（仓库地址变更）

---

.github/workflows/checklist.yml

（暂时？）移除 PR 自动回复

---

plugins/fastapi_mcdr/plugin_info.json

add fastapi_mcdr

---

plugins/restartserver/introduction-zh_cn.md
plugins/restartserver/introduction.md
plugins/restartserver/plugin_info.json

一个可以从其他服务器重启已经彻底崩溃服务器的插件，例如从镜像服重新唤起已经连命令行窗口彻底关闭的生存服
---
Briefly clarify plugin features in the …

restartserver

---

scripts/doc_gen.py
scripts/resources/lang/en_us.json
scripts/resources/lang/zh_cn.json

see 28fdcfe4daa0b56beebd81afb46461501cc6dfd3

use github blockquote in doc gen

---

readme.md
readme_cn.md

Maybe a good transition before https://github.com/MCDReforged/PluginCatalogue/pull/319.

doc: show a tip for new website.

---

plugins/requirements/plugin_info.json

新增 Requirements 插件

---

plugins/homo_calculator/plugin_info.json

Add plugin "homo_calculator"

---

readme.md
readme_cn.md

can be updated once the website is officially done

update main plugin catalog url

---

plugins/mirror_mcsmcdr/plugin_info.json

Add plugin mirror_mcsmcdr 添加插件MirrorMcsmcdR

---

plugins/baidu_netdisk_backup/plugin_info.json

add baidu_netdisk_backup plugin

---

plugins/plugin_info.json

Add plugin BatterySaver

---

plugins/region_file_manager/introduction.md
plugins/region_file_manager/plugin_info.json

Add Region_File_Manager (RFM)

---

plugins/mirror_mcsmcdr/plugin_info.json

修改MirrorMcsmcdR插件的introduction信息

---

plugins/command_aliases/plugin_info.json

add command_aliases

---

plugins/gugubot/plugin_info.json

基于QQChat旧版魔改和扩展的插件
功能比较定制化
魔改了大部分内容并增加了部分功能,于2022年11月9日至目前已维护将近两年
详情请查[文档](https://github.com/LoosePrince/PF-GUGUBot/blob/main/README.md)
---
- …

新增插件 GUGUBot

---

.github/workflows/scripts/pr_check.py

https://github.com/MCDReforged/PluginCatalogue/pull/370 之后发现 Workflow 输出的 log 是 DEBUG level ([例](https://github.com/MCDReforged/PluginCatalogue/actions/runs/10345610854/job/28633361020?pr=371))
故作此修改([效果](https://github.com/alex3236/PluginCatalogue/actions/runs/10345885378/job/28633578103?pr=1))

action: make logger level INFO

---

plugins/cq_qq_api/plugin_info.json
plugins/websocket_info_factory/plugin_info.json

Adding a WebSocket-based api to provide a connection between QQ and MCDR server, allowing other plugins to interact with QQ easily.
---
- 在介绍中简要阐明插件功能，在 …

Add `cq_qq_api`

---

plugins/just_kill_it/introduction-zh_cn.md
plugins/just_kill_it/introduction.md
plugins/just_kill_it/plugin_info.json

add `just_kill_it`

---

plugins/xevents/plugin_info.json

新增插件 `xEvents`

---

plugins/hat/plugin_info.json

Added plugin

---

plugins/g15t/plugin_info.json
plugins/xevents/plugin_info.json

新增插件 `G15T`

---

plugins/where2go/plugin_info.json

新增集成here vris和共享坐标点的插件Where2go

---

plugins/bili_live_helper/plugin_info.json

1.  全异步拉取B站弹幕
2. 支持多个玩家订阅各自的直播间,弹幕消息单独发送,互不干扰
3. 玩家可以随时启停弹幕姬
---
Briefly clarify plugin …

feat: :sparkles: add new plugin bili_live_helper

---

plugins/delayexe/plugin_info.json
plugins/kpi/plugin_info.json
plugins/loginproxy/plugin_info.json
plugins/smart_backup/plugin_info.json
plugins/smart_servertime/plugin_info.json
plugins/tpm/plugin_info.json

---
I have read and checked that my PR meets the requirements in the [Contributing Guidelines](CONTRIBUTING.md)

add introduction for @zyxkad plugins

---

plugins/delayexe/plugin_info.json
plugins/kpi/plugin_info.json
plugins/loginproxy/plugin_info.json
plugins/smart_backup/plugin_info.json
plugins/smart_servertime/plugin_info.json
plugins/tpm/plugin_info.json

---
I have read and checked that my PR meets the requirements in the [Contributing Guidelines](CONTRIBUTING.md)

fix readme typo for @zyxkad : md -> MD

---

plugins/whitelist_api/plugin_info.json

feat: :sparkles: add new plugin `whitelist_api`

---

plugins/iploc/plugin_info.json

Add plugin IPLocation | 添加插件IPLocation

---

plugins/beep/plugin_info.json
plugins/carpet_tick/plugin_info.json
plugins/crash_restart/plugin_info.json
plugins/diamond_calc/plugin_info.json
plugins/easy_bot_manager/plugin_info.json
plugins/fbs_plugin/plugin_info.json
plugins/here/plugin_info.json
plugins/homo_calculator/plugin_info.json
plugins/join_motd/plugin_info.json
plugins/join_motd_next/plugin_info.json
plugins/ledger_cleaner/plugin_info.json
plugins/location_marker/plugin_info.json
plugins/mc_uuid/plugin_info.json
plugins/mcdreforged_plugin_manager/plugin_info.json
plugins/minecraft_version_api/plugin_info.json
plugins/mirror_sync_reforged/plugin_info.json
plugins/multi_rcon_api/plugin_info.json
plugins/offline_whitelist/plugin_info.json
plugins/onebot_api/plugin_info.json
plugins/pcrc/plugin_info.json
plugins/permanent_backup/plugin_info.json
plugins/region_file_updater/plugin_info.json
plugins/showshowway/plugin_info.json
plugins/simple_calculator/plugin_info.json
plugins/simple_op/plugin_info.json
plugins/simple_translator/plugin_info.json
plugins/vault_bot/plugin_info.json
plugins/where_is/plugin_info.json
plugins/ye_announcement/plugin_info.json

Fix introduction of old plugins, by targeting introduction to their README file.

fix(meta): fix introduction for old plugins

---

plugins/snapshot_follower/plugin_info.json

Add plugin `snapshot_follower`

---

plugins/player_ip_logger/plugin_info.json

添加插件 player_ip_logger

---

plugins/bkchat_manager/plugin_info.json

此插件用于接管游戏内的聊天，定制聊天格式等，适用于BukkitAPI类型的服务端。
---

Add plugin BukkitChatManager

---

plugins/cleanroom_handler/introduction.md
plugins/cleanroom_handler/plugin_info.json
scripts/resources/labels.json
scripts/resources/lang/en_us.json
scripts/resources/lang/zh_cn.json

add cleanroom support

---

plugins/venture_chat_handler/plugin_info.json

新增插件 VentureChatHandler

---

plugins/guguwebui/plugin_info.json

Add plugin `guguwebui`.
Main Function: Provide a web UI for managing MC server config, MCDR config, and plugins' configs.
---

Add plugin `guguwebui`

---

plugins/cq_qq_api/plugin_info.json
plugins/gugubot/plugin_info.json
plugins/guguwebui/plugin_info.json
plugins/player_ip_logger/plugin_info.json

更新 `cq_qq_api`, `gugubot`, `guguwebui`, `player_ip_logger`:
- `introduction`: 参考 [alex3236的建议 ](https://github.com/MCDReforged/PluginCatalogue/pull/427#issuecomment-2467063097) 使用相对路径避免双份 README (省了不少工作量)
- `authors`: 统一作者名字 (已征求另一位作者同意)
> 谢谢 @alex3236 佬的建议哩
---

Change author name and introduction path for plugins

---

plugins/zip_backup/plugin_info.json

一个带有定时功能，可以把存档打成压缩包保存起来的插件
---

Add plugin Zip_Backup

---

plugins/leaves_handler/plugin_info.json

Add plugin-build handler for [Leaves](https://leavesmc.org/software/leaves) servers.
---

Add plugin LeavesHandler(id: leaves_handler)

---

plugins/matrix_sync/plugin_info.json

matrix_sync: 修改插件介绍信息的路径

---

plugins/salty_qq_chat/plugin_info.json

此插件可视为 [QQChat](https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/src/qq_chat) 的一个更完善的版本，未来将会加入更多实用的功能。
使用 `QQAPI`，遵守 `GPL 3.0` 协议，并且实际已得到作者可使用 `LGPL 3.0` 协议的特许。
有一点不太明白：`mcdreforged.plugin.json` 里头要不要加上 QQAPI 的作者呢？
---

Add plugin SaltyQQChat(id: salty_qq_chat)

---

plugins/tips/plugin_info.json

Add plugin Tips

---

plugins/salty_qq_chat/plugin_info.json

合得太快，没反应过来（
就加了个 API Label，没必要可以关掉（
---

fix: 添加 API Label

---

plugins/salty_qq_chat/plugin_info.json

Add English readme support

---

plugins/botkikai/plugin_info.json

新增插件botkikai

---

.github/workflows/scripts/utilities.py
scripts/meta/repos.py

fixes #456 
provide license information in plugin report.
---

feat(workflow): provide license information in plugin report

---

plugins/connect_core/plugin_info.json

新增插件: ConnectCore

---

plugins/im_api/plugin_info.json

A cross-platform instant messaging API
---

New plugin ImAPI, A cross-platform instant messaging API

---

plugins/pcc/plugin_info.json

add plugin pcc

---

plugins/mcsm_controller/plugin_info.json

add mcsm_controller

---

plugins/commandblock_handler/plugin_info.json

Add plugin Commandblock Handler

---

plugins/timed_restart/plugin_info.json

add timed_restart plugin

---

plugins/chat_with_ai/introduction-zh_cn.md
plugins/chat_with_ai/introduction.md
plugins/chat_with_ai/plugin_info.json

chat_with_ai

---

plugins/packet_parser/plugin_info.json

add packet_parser plugin

---

plugins/im_share_chat/plugin_info.json

Add a new plugin named "ImShareChat" with id "im_share_chat".
---

feat: add plugin im_share_chat

---

plugins/url_preview/plugin_info.json

feat: add plugin url_preview

---

.github/workflows/pull_request.yml

fix: replace `tj-actions/changed-files`

---

plugins/easybot_mcdr/plugin_info.json

添加插件 `easybot_mcdr`（由作者授权）

---

plugins/mccr/plugin_info.json

Add plugin MCDR Command Completer Reforged to PluginCatalogue

---

plugins/hitokoto/plugin_info.json

add hitokoto

---

plugins/telegram_chat/plugin_info.json

原本是 SaltyQQChat，后面因为 QQ 被封了转到小飞机，同时因为不再使用 QQAPI 因此新版本改掉了协议（原本 GPL 现在 MPL）
---

add: telegram_chat

---

plugins/cfgcmd/plugin_info.json

添加 `cfgcmd` 插件

---

plugins/ftp_backup/plugin_info.json

---
- [x ] 我已阅读并检查，此 PR 符合 [贡献指南](https://github.com/MCDReforged/PluginCatalogue/blob/master/CONTRIBUTING_zh_cn.md) 中的要求

添加插件ftp_backup

---

plugins/player_batch/plugin_info.json

添加插件player_batch

---

plugins/hat/plugin_info.json

更新 `Hat` 插件的 introduction

---

plugins/securercon/plugin_info.json

添加 `securercon` 插件

---

plugins/zhongbais_data_api/plugin_info.json

添加插件 zhongbaisDataAPI

---

plugins/async_rcon/plugin_info.json

Rcon client but async, modified from [RconConnection](https://docs.mcdreforged.com/zh-cn/latest/code_references/minecraft_tools.html#mcdreforged.minecraft.rcon.rcon_connection.RconConnection)
---

feat: add plugin AsyncRconClient(plugin_id: async_rcon)

---

plugins/file_manager/plugin_info.json

添加插件FileManager

---

plugins/extra_prime_backup/plugin_info.json

add plugin: extra_prime_backup

---

plugins/simple_tp/plugin_info.json

add plugin: simple_tp

---

plugins/simple_tp/plugin_info.json

修改插件信息的缩进问题，先前直接在网页上编辑导致缩进未格式化
---

chore: fix indentation inconsistencies

---

plugins/chat_link/plugin_info.json
plugins/chat_sync/plugin_info.json

add plugin: chat_link

---

plugins/mcdrpost/plugin_info.json

MCDRpost的原作者不再维护这个项目并授权给我维护，我来更新信息
授权见 Flyky/MCDRpost#10
---

MCDRpost 信息更新
